lol/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('lol.views',
    url(r'^$', 'index', name='index'),
    url(r'^upload/$', 'upload', name='upload'),
    url(r'^top/(?P<limit>\d+)/$', 'top', name='top'),
    url(r'^view/(?P<snippet_id>\d+)/$', 'view', name='view'),
    url(r'^bylang/(?P<language_name>\w+)/$', 'bylang', name='bylang'),
)

mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    url(r'^', include('lol.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)
urlpatterns += staticfiles_urlpatterns()

lol/models.py
from django.db import models
import hashlib

class Language(models.Model):
    name            = models.CharField(max_length=200)
    language_class  = models.CharField(max_length=200)
    
    def __unicode__(self):
        return u'%s' % (self.name)

class Snippet(models.Model):
    description = models.CharField(max_length=200)
    code        = models.TextField(max_length=1000)
    code_hash   = models.CharField(max_length=40, unique=True)
    language    = models.ForeignKey(Language)
    parent      = models.ForeignKey('self', null=True)
    leet        = models.IntegerField(default=0)
    lame        = models.IntegerField(default=0)
    gist_id     = models.IntegerField(default=0,null=True)
    approved    = models.BooleanField(default=False)
    
    def __unicode__(self):
        return u'%s' % (self.description)

    def _get_score(self):
        "Returns the diff of leet and lame"
        return self.leet - self.lame

    def validate(self):
        self.code_hash = hashlib.sha1(self.code.strip()).hexdigest()
        checkQuery = Snippet.objects.filter(code_hash=self.code_hash)
        
        return len(checkQuery) == 0
    
    score = property(_get_score)

lol/forms.py
from django import forms
from lol.models import Snippet, Language
from django.core.exceptions import ValidationError
import re

def validate_code(value):
    regex = re.compile("\r\n?|\n")
    match = regex.findall(value)
    
    if len(match) > 25:
        raise ValidationError("Sorry - too many lines.")
        
        
class UploadForm(forms.Form):
    description = forms.CharField(max_length=200)
    description.widget = forms.TextInput(attrs={"class":"input-block-level","required":""})
    inputCode = forms.CharField(widget=forms.Textarea(attrs={"rows":"10","class":"input-block-level"}),
                                validators=[validate_code],
                                max_length=1000)
    language = forms.ModelChoiceField(queryset=Language.objects.all().extra(select={'lower_name': 'lower(name)'}).order_by('lower_name'),
                                      empty_label="Select a language...")
    gist_id = forms.IntegerField(required=False)

lol/views.py
# Create your views here.
from django.http import HttpResponse
from django.template import Context, loader, RequestContext
from django.shortcuts import render, render_to_response, get_object_or_404, redirect
from lol.models import Snippet, Language
from django.core.exceptions import ValidationError
from lol.forms import UploadForm

def index(request):
    if request.method == 'GET':
        random = Snippet.objects.filter(approved=True).order_by('?')[0]
        thanks = False
        if request.session.has_key('thanks') and request.session['thanks']:
            request.session['thanks'] = False
            thanks = True
        return render_to_response('index.html', {'snippet': random, 'thanks': thanks},
                                  context_instance=RequestContext(request))
    elif request.method == 'POST':
        bias = request.POST['submitButton']
        snippet_id = request.POST['snippet_id']
        s = get_object_or_404(Snippet, pk=snippet_id)
        if (bias == 'Leet'):
            s.leet += 1
        elif(bias == 'Lame'):
            s.lame += 1
        s.save()
        return redirect('index')


def upload(request):
    if request.method == 'GET':
        form = UploadForm()
        return render(request, 'upload.html', {
            'form': form
        })
    elif request.method == 'POST':
        form = UploadForm(request.POST) 
        if form.is_valid():
            desc = form.cleaned_data['description']
            formCode = form.cleaned_data['inputCode']
            lang = form.cleaned_data['language']
            gistId = form.cleaned_data['gist_id']
            if(gistId):
                s = Snippet(code=formCode.strip(), description=desc.strip(), gist_id=gistId, language=lang)
            else:
                s = Snippet(code=formCode.strip(), description=desc.strip(), language=lang)
            if s.validate():
                s.save()
            else:
                return render(request, 'upload.html', {
                    'form':                form,
                    'error_message':       "Looks like we already have that code in our system." ,
                    'error_message_title': "Oops sorry!"
                })
            request.session['thanks'] = True
            return redirect('index')
        else:
            return render(request, 'upload.html', {
                'form': form
            })

def top(request, limit):
    limit = int(limit)
    top = sorted(Snippet.objects.filter(approved=True), key=lambda a: a.score, reverse=True)[:limit]
    return render_to_response('top.html', {'top': top, 'limit': limit},
                              context_instance=RequestContext(request))

def view(request, snippet_id):
    snippetList = Snippet.objects.filter(pk=snippet_id).filter(approved=True)
    if len(snippetList) == 1:
        return render_to_response('view.html', {'snippet': snippetList[0]},context_instance=RequestContext(request))
    else:
        return redirect('index')

def bylang(request, language_name):
    lang = get_object_or_404(Language, name=language_name)
    snippet = Snippet.objects.filter(language=lang).filter(approved=True).order_by('?')[0]
    return render_to_response('index.html', {'snippet': snippet},context_instance=RequestContext(request))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>{% block title %}{% endblock %}</title>
{% load staticfiles %}
<link href="{% static 'css/prettify.css' %}" type="text/css" rel="stylesheet" />
<script type="text/javascript" src="{% static 'js/prettify.js' %}"></script>
{% block extrastyle %}{% endblock %}
{% block extrahead %}{% endblock %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Bootstrap -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
<link href="{% static 'css/bootstrap-responsive.min.css' %}" rel="stylesheet" media="screen">
<link href="{% static 'css/lol.css' %}" rel="stylesheet" media="screen">
<link href="{% static 'css/sunburst.css' %}" rel="stylesheet">
</head>

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}" {% block onload %}{% endblock %}>
<div id="wrap">
<!-- Container -->
{% load tags %}
    <!-- Header -->
    <div id="header">
        <div class="container">
            <div class="masthead">
              <div class="navbar">
                <div class="navbar-inner">
                  <div class="container">
                    <ul class="nav">
                      <li class="{% block active_random %}{% endblock %}"><a href="{% url index %}">Random LoL</a></li>
                      <li class="{% block active_top %}{% endblock %}"><a href="{% url top 10 %}">Top 10</a></li>
                      <li class="{% block active_upload %}{% endblock %}"><a href="{% url upload %}">Add Yours!</a></li>
                    </ul>
                  </div>
                </div>
              </div><!-- /.navbar -->
            </div>
        
            <div id="branding">
            {% block branding %}{% endblock %}
            </div>
        </div>
    </div>
    <!-- END Header -->

    <!-- Content -->
    <div id="content">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}

         
    </div>
    <div id="push"></div>
</div>
</div>
    <!-- END Content -->

    {% block footer %}
    <div id="footer">
        <div class="container">
            <div class="row">
                <div class="span5">
                    <small>This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/us/">Creative <br>Commons Attribution 3.0 United States License</a>.</small>
                </div>
                <div class="span1 offset6">
                    <nobr><small><a href="mailto:contact@leetorlame.com">Contact Us</a></small></nobr>
                </div>
            </div>
        </div>
    </div>{% endblock %}

<!-- END Container -->
<script src="http://code.jquery.com/jquery.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block eofjavascript %}{% endblock %}
{% if tracking_enabled %}
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '{{ tracking_account }}']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
{% endif %}
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}Leet or Lame{% endblock %}
{% load staticfiles %}

{% block active_random %}active{% endblock %}
{% block onload %}onload="prettyPrint()"{% endblock %}

{% block eofjavascript %}

<script type="text/javascript" src="{% static 'js/lang-css.js' %}"></script>
<script type="text/javascript" src="{% static 'js/lang-go.js' %}"></script>
<script type="text/javascript" src="{% static 'js/lang-hs.js' %}"></script>
<script type="text/javascript" src="{% static 'js/lang-lisp.js' %}"></script>
<script type="text/javascript" src="{% static 'js/lang-scala.js' %}"></script>
<script type="text/javascript" src="{% static 'js/lang-sql.js' %}"></script>

{% endblock %}

{% block branding %}
<div class="mainHeader">
    <h1 id="site-name">Leet or Lame</h1>
</div>
{% endblock %}
 
{% block content %}
<div class="container">
    {% if thanks %}
    <div class="container">
        <div class="row">
            <div class="span2"></div>
            <div class="span8">
                <div class="alert alert-success">
                  <a href="#" class="close" data-dismiss="alert">&times;</a>
                  Thanks for adding new code to the system.<br>
                  Come back soon to vote for it!
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    <div class="row-fluid">
        <div class="span2"></div>
        <div class="span8">  
            <div class="description">
                <a href="{% url view snippet.id %}">
                    {{ snippet.description}}&nbsp;&nbsp;({{ snippet.language.name}})
                </a>
            </div>
        </div>
    </div>
    <form action="{% url index %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="snippet_id" value="{{ snippet.id }}" />
        <div class="row-fluid">
            <div class="span2" style="text-align:center">
                <input type="submit" name="submitButton" value="Leet" class="lolButton"/>
            </div>
            <div class="span8">
                <pre class="prettyprint"><code class="{{ snippet.language.language_class}}">{{ snippet.code }}</code></pre>
            </div>
            <div class="span2" style="text-align:center">
                <input type="submit" name="submitButton" value="Lame" class="lolButton" />
            </div>
        </div>
    </form>
{% endblock %}

templates/top.html
{% extends "base.html" %}

{% load tags %}
{% load staticfiles %}

{% block title %} Top {{ limit }} Snippets {% endblock %}

{% block active_top %}active{% endblock %}
{% block onload %}onload="prettyPrint()"{% endblock %}

{% block eofjavascript %}

<script type="text/javascript" src="{% static 'js/lang-css.js' %}"></script>
<script type="text/javascript" src="{% static 'js/lang-go.js' %}"></script>
<script type="text/javascript" src="{% static 'js/lang-hs.js' %}"></script>
<script type="text/javascript" src="{% static 'js/lang-lisp.js' %}"></script>
<script type="text/javascript" src="{% static 'js/lang-scala.js' %}"></script>
<script type="text/javascript" src="{% static 'js/lang-sql.js' %}"></script>

{% endblock %}

{% block branding %}
<div class="mainHeader">
    <h1 id="site-name">Leet or Lame</h1>
</div>
{% endblock %}

{% block content %}
<div class="container"> 
    <ol>
    {% for snippet in top %}
    <div class="row-fluid">
        <div class="span7">  
            <li> 
                <div class="description">
                    <a href="{% url view snippet.id %}">
                        {{ snippet.description}}&nbsp;&nbsp;({{ snippet.language.name}})
                    </a>
                    &nbsp;&nbsp;Leetness: {{ snippet.score }}
                </div>
                <pre class="prettyprint"><code class="{{ snippet.language.language_class}}">{{ snippet.code|tenlines }}</code>
                </pre>
            </li>
        </div>
    </div>
    {% endfor %}
    </ol>
</div>
{% endblock %}

templates/upload.html
{% extends "base.html" %}

{% block title %}Add yours!{% endblock %}
{% load staticfiles %}

{% block branding %}
<div class="mainHeader">
    <h1 id="site-name">Leet or Lame</h1>
</div>
{% endblock %}

{% block active_upload %}active{% endblock %}

{% block content %}

{% if error_message %}
<div class="container">
    <div class="row">
	<div class="span3"></div>
        <div class="span7">
	    <div class="alert">
	      <a href="#" class="close" data-dismiss="alert">&times;</a>
	      <strong>{{ error_message_title }}</strong> {{ error_message }}
	    </div>
	</div>
    </div>
</div>
{% endif %}

<form action="{% url upload %}" method="post" class="form-horizontal">
{% csrf_token %}
    {{ form.non_field_errors }}
    <div class="container">
        <div class="row">
            <div class="span1"></div>
            <div class="span9">
                <div class="control-group {% if form.description.errors %}error{% endif %}">
                    <label class="control-label" for="id_description">Description:</label>
                    <div class="controls">
			{{ form.description }}
			{% if form.description.errors %}
			<span class="help-inline">{{ form.description.errors }}</span>
			{% endif %}
		    </div>
                </div>
                <div class="control-group {% if form.inputCode.errors %}error{% endif %}">
                    <label class="control-label" for="inputCode">Code:</label>
		    <div class="controls">
			{{ form.inputCode }}
                        <div class="lineCounter">You have <span id="counter">25</span> lines left.</div>
			{% if form.inputCode.errors %}
			<span class="help-inline">{{ form.inputCode.errors }}</span>
			{% endif %}
		    </div>
                </div>
                <div class="control-group {% if form.language.errors %}error{% endif %}">
		    <label class="control-label" for="language_id">Language:</label>
                    <div class="controls">
			{{ form.language }}
			{% if form.language.errors %}
			<span class="help-inline">{{ form.language.errors }}</span>
			{% endif %}
                    </div>
		</div>
		<div class="control-group {% if form.gist_id.errors %}error{% endif %}">
			<label class="control-label" for="gistId">Import gist by id:</label>
			<div class="controls">
			    {{ form.gist_id }}
			    <button type='button' id="import_gist">Import</button>
			    {% if form.gist_id.errors %}
			    <span class="help-inline">{{ form.gist_id.errors }}</span>
			    {% endif %}
			</div>
		</div>
            </div>
        </div>
        <div class="row">    
            <div class="span1 center">
                <input type="submit" value="Submit"/>
            </div>
        </div>
    </div>
</form>

{% endblock %}



{% block eofjavascript %}
<!-- Textarea count from https://bitbucket.org/MostThingsWeb/textarea-line-count/wiki/Home -->
<script type="text/javascript" src="{% static 'js/jquery.TextareaLineCount.1.4.1.min.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){
    $('#import_gist').click(function(){ 
        code_box = $("textarea[name='inputCode']");
        description_box = $("input[name='description']");
        language_box = $("select[name='language']");
        gist_id = $("input[name='gist_id']").val();
        url = "https://api.github.com/gists/" + gist_id;
        $.ajax({ 
            url      : url, 
            dataType : 'jsonp', 
            timeout  : 10000,
            success: function(response) {
                if(response.data['description']){
                    description_box.val(response.data['description']);
                }
                for (file in response.data.files) {
                    if (response.data.files.hasOwnProperty(file)) {
                        var lang = response.data.files[file].language;
                        if(lang){
                            var value = $("select option").filter(function() {
                                  return $(this).text() === lang;
                            }).first().attr("value");
                            language_box.val(value);
                        }
                        code_box.val(response.data.files[file].content);
                    }
                }
            }
        }); 
    });
});

$(document).ready(function(){
    $('#id_inputCode').bind('input propertychange', monitorLines);
    monitorLines();
});

function monitorLines() {
    var result = $.countLines("#id_inputCode");
    if(result.actual == 1 && $('#id_inputCode').val() == '') {
	$('#counter').text(25);
    }
    else {
	$('#counter').text(25 - result.actual);
    }
}

</script>

{% endblock %}

templates/view.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Leet or Lame{% endblock %}
{% block onload %}onload="prettyPrint()"{% endblock %}

{% block eofjavascript %}

<script type="text/javascript" src="{% static 'js/lang-css.js' %}"></script>
<script type="text/javascript" src="{% static 'js/lang-go.js' %}"></script>
<script type="text/javascript" src="{% static 'js/lang-hs.js' %}"></script>
<script type="text/javascript" src="{% static 'js/lang-lisp.js' %}"></script>
<script type="text/javascript" src="{% static 'js/lang-scala.js' %}"></script>
<script type="text/javascript" src="{% static 'js/lang-sql.js' %}"></script>

{% endblock %}

{% block branding %}
<div class="mainHeader">
    <h1 id="site-name">Leet or Lame</h1> 
</div>
{% endblock %}
 
{% block content %}
<div class="container">
    <div class="row-fluid">
        <div class="span2">
        </div>
        <div class="span7">  
            <div class="description">{{ snippet.description}}&nbsp;&nbsp;({{ snippet.language.name}})<br>
            Leetness: {{ snippet.score }}</div>
        </div>
        <div class="span1">
             <a href="https://twitter.com/share" class="twitter-share-button" data-text="Check out this code!" data-count="none" data-dnt="true">Tweet</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        </div>
    </div>
     <div class="row-fluid">
        <div class="span2">
        </div>
        <div class="span8">
            <pre class="prettyprint"><code class="{{ snippet.language.language_class}}">{{ snippet.code }}</code>
            </pre>
        </div>
    </div>
</div>
{% endblock %}